import { HeroTroopApeData } from "./types";

export const HERO_TROOP_APES_LIST: HeroTroopApeData[] = [
  {
    size: "20vh",
    zIndex: 1,
    centerTranslation: "41%",
    traits: {
      ape: "Brown",
      head: "Gamblers Hat",
      eyes: "Metallic Visor",
      ears: "Nothing",
      mouth: "Jaws",
    },
  },
  {
    size: "26vh",
    zIndex: 2,
    centerTranslation: "32.5%",
    traits: {
      ape: "Red",
      head: "Nothing",
      eyes: "VR",
      ears: "Nothing",
      mouth: "Nothing",
    },
  },
  {
    size: "32vh",
    zIndex: 3,
    centerTranslation: "22.5%",
    traits: {
      ape: "Albino",
      head: "Military Hat",
      eyes: "Stoned",
      ears: "Nothing",
      mouth: "Smile",
    },
  },
  {
    size: "37vh",
    zIndex: 4,
    centerTranslation: "12.5%",
    traits: {
      ape: "Mutant",
      head: "Nothing",
      eyes: "Angry Visor",
      ears: "Nothing",
      mouth: "Nothing",
    },
  },
  {
    size: "40vh",
    zIndex: 5,
    centerTranslation: "0px",
    traits: {
      ape: "Brown",
      head: "Crown",
      eyes: "Rainbow Visor",
      ears: "Nothing",
      mouth: "Blunt",
    },
  },
  {
    isLookingRight: true,
    size: "37vh",
    zIndex: 4,
    centerTranslation: "-12.5%",
    traits: {
      ape: "Robot",
      head: "Nothing",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Red NT Mask",
    },
  },
  {
    isLookingRight: true,
    size: "32vh",
    zIndex: 3,
    centerTranslation: "-22.5%",
    traits: {
      ape: "Zombie",
      head: "Nothing",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Cigar",
    },
  },
  {
    isLookingRight: true,
    size: "26vh",
    zIndex: 2,
    centerTranslation: "-32.5%",
    traits: {
      ape: "Black",
      head: "Saka",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Banana",
    },
  },
  {
    isLookingRight: true,
    size: "20vh",
    zIndex: 1,
    centerTranslation: "-41%",
    traits: {
      ape: "Robot",
      head: "Cap",
      eyes: "Virtual",
      ears: "Nothing",
      mouth: "Green NT Mask",
    },
  },
];

export const HERO_TROOP_APES_LIST_MOBILE: HeroTroopApeData[] = [
  {
    size: "26vh",
    zIndex: 2,
    centerTranslation: "32.5%",
    traits: {
      ape: "Red",
      head: "Nothing",
      eyes: "VR",
      ears: "Nothing",
      mouth: "Nothing",
    },
  },
  {
    size: "32vh",
    zIndex: 3,
    centerTranslation: "22.5%",
    traits: {
      ape: "Albino",
      head: "Military Hat",
      eyes: "Stoned",
      ears: "Nothing",
      mouth: "Smile",
    },
  },
  {
    size: "37vh",
    zIndex: 4,
    centerTranslation: "12.5%",
    traits: {
      ape: "Mutant",
      head: "Nothing",
      eyes: "Angry Visor",
      ears: "Nothing",
      mouth: "Nothing",
    },
  },
  {
    size: "40vh",
    zIndex: 5,
    centerTranslation: "0px",
    traits: {
      ape: "Brown",
      head: "Crown",
      eyes: "Rainbow Visor",
      ears: "Nothing",
      mouth: "Blunt",
    },
  },
  {
    isLookingRight: true,
    size: "37vh",
    zIndex: 4,
    centerTranslation: "-12.5%",
    traits: {
      ape: "Robot",
      head: "Nothing",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Red NT Mask",
    },
  },
  {
    isLookingRight: true,
    size: "32vh",
    zIndex: 3,
    centerTranslation: "-22.5%",
    traits: {
      ape: "Zombie",
      head: "Nothing",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Cigar",
    },
  },
  {
    isLookingRight: true,
    size: "26vh",
    zIndex: 2,
    centerTranslation: "-32.5%",
    traits: {
      ape: "Black",
      head: "Saka",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Banana",
    },
  },
];
